export function regionRestrict(regions: string[]) {
  const body = {
    Version: "2012-10-17",
    Statement: [
      {
        Condition: {
          StringNotEquals: {
            "aws:RequestedRegion": regions,
          },
        },
        Resource: "*",
        Effect: "Deny",
        NotAction: [
          "a4b:*",
          "acm:*",
          "aws-marketplace-management:*",
          "aws-marketplace:*",
          "aws-portal:*",
          "budgets:*",
          "ce:*",
          "chime:*",
          "cloudfront:*",
          "config:*",
          "cur:*",
          "directconnect:*",
          "ec2:DescribeRegions",
          "ec2:DescribeTransitGateways",
          "ec2:DescribeVpnGateways",
          "fms:*",
          "globalaccelerator:*",
          "health:*",
          "iam:*",
          "importexport:*",
          "kms:*",
          "mobileanalytics:*",
          "networkmanager:*",
          "organizations:*",
          "chatbot:*",
          "pricing:*",
          "route53-recovery-control-config:*",
          "route53-recovery-readiness:*",
          "route53-recovery-cluster:*",
          "route53:*",
          "route53domains:*",
          "s3:GetBucketPublicAccessBlock",
          "s3:ListAllMyBuckets",
          "s3:GetBucketLocation",
          "s3:GetAccountPublic",
          "s3:DeleteMultiRegionAccessPoint",
          "s3:DescribeMultiRegionAccessPointOperation",
          "s3:GetMultiRegionAccessPoint",
          "s3:GetMultiRegionAccessPointPolicy",
          "s3:GetMultiRegionAccessPointPolicyStatus",
          "s3:ListMultiRegionAccessPoints",
          "s3:GetStorageLensConfiguration",
          "s3:GetStorageLensDashboard",
          "s3:ListStorageLensConfigurations",
          "s3:GetAccountPublicAccessBlock",
          "s3:PutAccountPublic",
          "s3:PutAccountPublicAccessBlock",
          "shield:*",
          "sts:*",
          "support:*",
          "supportplans:*",
          "trustedadvisor:*",
          "waf-regional:*",
          "waf:*",
          "wafv2:*",
          "access-analyzer:*",
        ],
        Sid: "regionDeny",
      },
    ],
  };
  return body;
}
